package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.Signal;

public class ATestSignalSignal extends Signal {

  public ATestSignalSignal() {
    this.setName("ATestSignal");
    this.setDescription("aaaa");
    this.AddActor("ENP");
  }
}
